### ISSUE TITLE
Cannot save settings

### ISSUE THREAD

**Issue by AmomentOfMusic** [boan-anbo/Zotero-Citation-Picker-for-Windows#1]
When I go to save settings, I get stuck in an infinite loop - everytime I click save, it tells settings have been set, and then returns me to the initial screen. When I go to use the picker, it is still using the default settings.

Otherwise - I am impressed by how quick it is!

**Comment by boan-anbo** [comment]
Hi there! That's probably due the app being unable to create an .ini file to store the settings. Are you running the app with Administration privileges?

I just added a new version that will stop the app if it cannot find the .ini file. You can give it a try.

**Comment by AmomentOfMusic** [comment]
I just tried the new version and it worked - though windows did at first try to block the app from running at all, and I had to tell Windows it was okay. Didn't try running it with administrators priviledges right away - but either way it is now working, saving my settings and creating the .ini file
