### ISSUE TITLE
ODF scan plugin with insert citation not working

### ISSUE THREAD

**Issue by eriksdev1** [boan-anbo/Zotero-Citation-Picker-for-Windows#2]
How can I access the ODT scan locator settings ? I tried to insert the citation with page numbers but was not possible, I´m using this settings:
![image](https://user-images.githubusercontent.com/45124393/73893489-7158b580-483f-11ea-9940-a7fc1bb745a4.png)

**Comment by boan-anbo** [comment]
Hi my apologies for the delayed response. With default setting, the reference is inserted (pasted) directly to where your keyboard caret is. Alternatively, you can open the settings and uncheck automatic insertion. That way, the reference is copied to your clipboard. You can just Ctrl + V to paste it wherever you like.
